### ISSUE TITLE
Failed to install iHateMoney

### ISSUE THREAD

**Issue by opi** [YunoHost-Apps/ihatemoney_ynh#1]
Running python 2.7.3; My Yunohost instance is not really a clean & stable one. I have the daily repo in my sources.list, but I'm not sure it is related.

Here is my full installation log : http://paste.yunohost.org/rikexoveti.coffee
If you search for "error" inside this log, it only occurs once : `SyntaxError: ('invalid syntax', ('/opt/yunohost/ihatemoney/venv/lib/python2.7/site-packages/raven/transport/aiohttp.py', 31, 37, '    def __init__(self, parsed_url, *, verify_ssl=True, resolve=True,\n'))`

It's more a Yunohost issue rather than a ihatemoney_ynh issue, but f I try to reinstall, installation failed earlier with this error : `useradd: user 'ihatemoney' already exists`. It's because the remove script is not run when the installation one failed.

**Comment by anmol26s** [comment]
I have the same issue. Here is the log.
https://datamol.in/zerobin/?5d4feeaec9b61933#Q16e8+of0MIUSqG8GqtIM0OlLljLEdlOqDO9yB24nQ4=

**Comment by JocelynDelalande** [comment]
@anmol26s not sure it's the same issue as @opi your issue commes from the fact you try installing on an already installed of half-installed ihatemoney_ynh instance. I Opened #4  for your issue.

Regards,

Jocelyn

**Comment by JocelynDelalande** [comment]
@opi is that all the log you get ? it seems to stop [here](https://github.com/JocelynDelalande/ihatemoney_ynh/blob/master/scripts/install#L36) without error, which is quite odd

**Comment by JocelynDelalande** [comment]
@opi are you now able to re-install it ? (may require that you try twice, the first attempt being used to cleanup)

If it still does not work, try deleting the mysql db and run install again (may also require 2 runs).

**Comment by opi** [comment]
You're damn right. I must have ran it twice, but this time I got a perfectly running installation.

**Comment by JocelynDelalande** [comment]
@opi oh but there is no magic,  even runing it twice before would have failed. I patched the code yesterday to better handle failed install :-) (install script cleaning after itself).
