### ISSUE TITLE
Password setting for Admin

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/ihatemoney_ynh#18]
Hi team,
I'm trying to set up the admin panel to my operational install on Rpi3-Raspbian Wheezy. In modifying the ihatemoney.cfg  file, the doc says : "to generate the proper password HASH, use `ihatemoney generate_password_hash`" . But this command is not found on my Raspbian install. Is there something I don't get ?
Thanks for your lights on this matter !

**Comment by JocelynDelalande** [comment]
@Jaxom99 sorry for delay : that command is available from Ihatemoney >= 2, which is not yet packaged for ynh (ongoing here : #19 )

**Comment by JocelynDelalande** [comment]
Once we support v2.x we should add a setting on install to tweak that admin password by prompting it from installer. See also #24
