### ISSUE TITLE
New version 2.0 of IHM

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/ihatemoney_ynh#19]
New version 2.0 is now available! https://github.com/spiral-project/ihatemoney/releases
Do you think it is possible to release it in YNH?
Thx!

**Comment by JocelynDelalande** [comment]
@klorydryk of course it is possible ; but I have to take the time to do it, as 2.0 include backward-incompatible changes and introduce new features.

See also #16 #18 and IHM ChangeLog https://github.com/spiral-project/ihatemoney/blob/master/CHANGELOG.rst#20-2017-12-27

If you think you have the time & skills to Pull-request the upgrade, I'll happily review and merge it :)

**Comment by klorydryk** [comment]
I can try :)
(But I've never done a YNH package. It is important to update a package?)

**Comment by JocelynDelalande** [comment]
> I can try :)

Go ahead :-)

> (But I've never done a YNH package. It is important to update a
> package?)

Yes, the package points to a fixed version of the software, for
safety reasons : if the upstream gets updated, this installation
method could change, so the underlying system (config files,
database, paths…) have to adapt.

So as long as the package is not updated, ynh users are using an
old version of ynh.

**Comment by klorydryk** [comment]
J'avoue ne pas très bien comprendre la raison pour extraire le code de IHateMoney du dépôt ynh. Peut-être qu'en français je comprendrais mieux ? :)

**Comment by JocelynDelalande** [comment]
> J'avoue ne pas très bien comprendre la raison pour extraire le code de IHateMoney du dépôt ynh. Peut-être qu'en français je comprendrais mieux ? :)

Hm je veux bien répondre, et aucun souci pour le français. Mais si tu reformulais ou développais ta question je la comprendrais mieux également :-)

**Comment by klorydryk** [comment]
ah, mais peut-être que je comprends : tu expliques te baser sur un zip (version figée) du soft car tu ne veux pas télécharger directement le code du trunk à l'installation ?
Ok, ça me semble logique.

Par contre, que veux-tu dire par "tant que le paquet n'est pas mis à jour, les utilisateurs ynh utilisent une ancienne version de ynh" ? Tu veux dire une ancienne version de IHateMoney ?

**Comment by JocelynDelalande** [comment]
> ah, mais peut-être que je comprends : tu expliques te baser sur un zip (version figée) du soft car tu ne veux pas télécharger directement le code du trunk à l'installation ?
> Ok, ça me semble logique.

Oui, c'est ça. Ça permet également de vérifier l'intégrité de la source.

D'ailleurs avec la version 2.0 de Ihatemoney, la méthode d'installation officielle change : on peut directement faire un `pip install ihatemoney`. Plus besoin de télécharger une archive "à la main". Par contre, inconvénient, cette méthode avec *pip* ne permet pas (à ma connaissance) de vérifier l'intégrité du code télécharger à l'aide d'une somme de contrôle. 

Donc dans la mesure où l'on a déjà, dans l'app ynh, le code pour gérer l'archive, peut-être vaut-il mieux continuer avec l'archive (ça fonctionne toujours, et ça continuera de fonctionner).

> Par contre, que veux-tu dire par "tant que le paquet n'est pas mis à jour, les utilisateurs ynh utilisent une ancienne version de ynh" ? Tu veux dire une ancienne version de IHateMoney ?

Oui, pardon.
