### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/ihatemoney_ynh#23]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/jenkins/job/ihatemoney%20(Community)/37/consoleFull

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by JocelynDelalande** [comment]
@maniackcrudelis thanks for the notice and sorry for the delay.

I cannot reproduce the failure localy, do you have any trace/log of the failure, or has everything been wiped from the CI ?

**Comment by maniackcrudelis** [comment]
The log is still [here](https://ci-apps.yunohost.org/jenkins/logs/github.com_YunoHost-Apps_ihatemoney_ynh_complete.log)

**Comment by JocelynDelalande** [comment]
@maniackcrudelis lovely, thanks :-)
