### ISSUE TITLE
Ask for new settings values

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/ihatemoney_ynh#24]
With new ihatemoney comes new optional settings in conf file.

Here are defaults for those (actually, we do not offer tweaking through installer)
```
ACTIVATE_DEMO_PROJECT = True
ADMIN_PASSWORD = ""
ALLOW_PUBLIC_PROJECT_CREATION = True
ACTIVATE_ADMIN_DASHBOARD = False
```

**Comment by yalh76** [comment]
Now config file is updated during upgrade
https://github.com/YunoHost-Apps/ihatemoney_ynh/blob/2fac3e00499f5b55d9171143df3e60c88fe7816b/scripts/upgrade#L184
