### ISSUE TITLE
Support stretch / ynh 3.x

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/ihatemoney_ynh#25]
TODO-list:

- [x] Adapt static path in nginx.conf
- [x] Handle venv in case of ynh upgrade from yng 2.x to 3.x (and thus from python 3.4 to python 3.5, probably breaking the venv totally)
- [x] any other ?

Relates #20

**Comment by klorydryk** [comment]
Do you plan to support Stretch so far ? I'll try to work on it next week, but can't guarantee to make it work XD

**Comment by JocelynDelalande** [comment]
Cool, go ahead, I have limited time to work on it those days, and I wanted to make it pass the Jessie CI before starting to work on stretch (but I'm having hard time with YNH CIs).

In short : you are very welcome, go ahead, and I will try to provide help if you need some :-).

See also https://github.com/YunoHost/apps/pull/553

**Comment by JocelynDelalande** [comment]
Done in recent commits :-) installation/upgrade (from jessie) uninstallation and backup/restore works !
