### ISSUE TITLE
List this package on the apps page of yunohost

### ISSUE THREAD

**Issue by almet** [YunoHost-Apps/ihatemoney_ynh#29]
For a reason I don't understand, it's not listed there at the moment.

**Comment by almet** [comment]
Hmm, my bad, it's listed there but:
- is marked as "not working", not sure if it works?
- is spelled "I Hate Money" and the search doesn't return it if I search for "Hate" or "Money", or "ihatemoney".

**Comment by JocelynDelalande** [comment]
It does not work (yet) with latest major version of YNH. That is why it is marked as not working. Work in progress :-)

**Comment by almet** [comment]
Thanks for the heads up!

**Comment by JocelynDelalande** [comment]
It is listed again (and package cleaned, and up to date with upstream 3.0, and working with both YunoHost 2.x and 3.x \o/).
