### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/ihatemoney_ynh#37]
I have no clue when and how it happened, but as all other services are working well, my IHateMoney install works no more, and displayed a 404.

Perhaps since I updated Yunohost to v4...

I tried to backup / remove / restore, but nothing better.

I finally had to remove the application, make a fresh installation, then import the database from the Yunohost backup to get it back from the dead.

I opened this issue in case it could help.

**Comment by JocelynDelalande** [comment]
Thanks for reporting !

Sorry, cannot reproduce :-(.

Did you had custom nginx configuration ?

My dev/prod servers/instances are also with ynh 4.x also. I'll let this ticket open for some time if someone hits the same bug or manage to reproduce, otherwise will close after a certain time.

**Comment by klorydryk** [comment]
No custom nginx config, nope :s

**Comment by SiM** [comment]
@klorydryk have you tried to force an upgrade ?
`yunohost app upgrade ihatemoney -u https://github.com/YunoHost-Apps/ihatemoney_ynh/tree/master`
You need to do this after upgrading to YNH 4.x from 3.x (to recreate python venv if I understood well)

**Comment by klorydryk** [comment]
Sorry for the delay, I forgot to answer, it worked like this, @SiM , thanks !
