### ISSUE TITLE
Should handle gracefuly a re-install from a previous try

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/ihatemoney_ynh#4]
As showed by @anmol26s in #1 and his/her log : https://datamol.in/zerobin/?5d4feeaec9b61933#Q16e8+of0MIUSqG8GqtIM0OlLljLEdlOqDO9yB24nQ4= , if a first install fails, you cannot uninstall and you cannot reinstall either… you're stuck in [limbo](https://en.wikipedia.org/wiki/Limbo) !

**Comment by JocelynDelalande** [comment]
I worked on that issue @anmol26s does it fixes it for you ?

**Comment by anmol26s** [comment]
Hi @JocelynDelalande 
Thank you so much. The app is working now.

**Comment by JocelynDelalande** [comment]
@anmol26s you're welcome, thanks for reporting :)
