### ISSUE TITLE
Update to ihatemoney 5.1.1

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/ihatemoney_ynh#42]
new stuff on ihatemoney side :)

**Comment by Salamandar** [comment]
I saw something in the release notes :
https://github.com/spiral-project/ihatemoney/releases/tag/5.0.0
>  Drop support for MySQL

-> ACK ! We'll need to dump the mysql database and create a MariaDB database instead. Really touchy.

**Comment by JocelynDelalande** [comment]
I don't get it, from what I see on my ynh servers, mysql already got replaced by mariadb, even if the running binary is called /usr/sbin/mysqld it [belongs to the mariadb package](https://packages.debian.org/search?searchon=contents&keywords=%2Fusr%2Fsbin%2Fmysqld&mode=path&suite=oldstable&arch=any).

To what I get, on stable ynh instances, our package is already running on mariadb. This change seems like a no-op from our ynh packaging standpoint.

@Salamandar Maybe I'm missing something ?

**Comment by Salamandar** [comment]
Hah ! Well i'm sorry about this. I was still seing things about mysql, didn't search any further.

**Comment by yalh76** [comment]
already at 5.2.0~ynh1
