### ISSUE TITLE
Warning: 'yunohost app initdb' is deprecated and will be removed in the future

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/ihatemoney_ynh#6]
And maybe others warnings...

**Comment by JocelynDelalande** [comment]
Oops, those commits were not related to #6

**Comment by anmol26s** [comment]
ERROR 1007 (HY000) at line 1: Can't create database 'ihatemoney'; database exists
Error: Installation failed

**Comment by JocelynDelalande** [comment]
@anmol26s Thanks for reporting.
Please open a new ticket and provide more context details. Your error you seems unrelated to the warning I opened the ticket for.

**Comment by anmol26s** [comment]
I think my issue is related to this : https://github.com/jeromelebleu/mediagoblin_ynh/issues/6#issuecomment-231854184
Giving the value 0 or 1 makes installation successful and app works.
Thanks

**Comment by JocelynDelalande** [comment]
@anmol26s I don't think it's related to the issue I opened ; please create a new issue with the relevant elements.
