### ISSUE TITLE
Update to 6.1.3 or 6.1.5

### ISSUE THREAD

**Issue by Jojo144** [YunoHost-Apps/ihatemoney_ynh#68]
Hi,
Should you update the script to I Hate Money 6.1.3 or 6.1.5?
I can test it after if you want.
Thanks

**Comment by JocelynDelalande** [comment]
Why not :)

Le 4 août 2024 14:16:30 GMT+02:00, Jojo144 ***@***.***> a écrit :
>Hi,
>Should you update the script to I Hate Money 6.1.3 or 6.1.5?
>I can test it after if you want.
>Thanks
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost-Apps/ihatemoney_ynh/issues/68
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Jocelyn
