### ISSUE TITLE
502 Bad Gateway - nginx

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/ihatemoney_ynh#7]
Hi,
After an update, I get this error when trying to access I hate money. I have this in nginx log : 
https://plaf.fr/zerobin/?28fdce5d32b9cc7a#FidaCREKC1BAKPLB3lFXTZDq55wW4cV+weJSzMqSO0w=
Any idea ?

**Comment by JocelynDelalande** [comment]
> After an update, I get this error when trying to access I hate
> money. I have this in nginx log :
> https://plaf.fr/zerobin/?28fdce5d32b9cc7a#FidaCREKC1BAKPLB3lFXTZDq55wW4cV+weJSzMqSO0w=
> Any idea ?

Can you provide the content of the files in /var/log/supervisor ?

**Comment by tomdereub** [comment]
Finally, the problem has been solved with a reboot, it's working fine.
Sorry !

**Comment by JocelynDelalande** [comment]
> Finally, the problem has been solved with a reboot, it's
> working fine. Sorry !
> 
> From the app standpoint, that's not realy fine a reboot is
> required after upgrade to get it working :-p.

If you have any log/ useful piece of information please post it
here :-).

**Comment by tomdereub** [comment]
/var/log/supervisor/supervisord.log : 
https://plaf.fr/zerobin/?280bd347e6119c21#uNJ3xrBjSLwTD+9QoUSGvTlLRzzZJkCMMviEmRguRtI=
/var/log/supervisor/budget-stderr---supervisor-iQh8AR.log and budget-stdout---supervisor-9eH5NU.log are empty.
Hope it helps...

**Comment by JocelynDelalande** [comment]
@tomdereub not realy, sadly. 

Closing for now, thanks for taking time :-)
