### ISSUE TITLE
Changement du propriétaire de l'app

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/ihatemoney_ynh#8]
Bonjour, 
Il serait bien, pour une meilleure gestion des applications et une meilleure gestion des contributions, que toutes les apps rejoignent l'organisation **Yunohost-Apps**.
Merci,
frju365
_____
Hello,
To manage in a better way the contributions and the Apps, we invite you to change the ownership of your app  to **Yunohost-Apps** Organization. 
Thanks,
frju365

**Comment by JocelynDelalande** [comment]
Fair enough. I'm going to do that if I can :)

**Comment by JocelynDelalande** [comment]
done
